/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HealthEntry = IDL.Record({
  'bp' : IDL.Text,
  'weight' : IDL.Float64,
  'waterIntake' : IDL.Float64,
  'steps' : IDL.Nat,
  'timestamp' : IDL.Int,
  'sleepHours' : IDL.Float64,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'interests' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'ageGroup' : IDL.Text,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHealthEntry' : IDL.Func([HealthEntry], [], []),
  'addMessage' : IDL.Func([Message], [], []),
  'addReminder' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearChatHistory' : IDL.Func([], [], []),
  'computeHealthScore' : IDL.Func([], [IDL.Nat], ['query']),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Int],
      [],
      [],
    ),
  'deleteReminder' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getHealthEntries' : IDL.Func([], [IDL.Vec(HealthEntry)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'toggleReminder' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HealthEntry = IDL.Record({
    'bp' : IDL.Text,
    'weight' : IDL.Float64,
    'waterIntake' : IDL.Float64,
    'steps' : IDL.Nat,
    'timestamp' : IDL.Int,
    'sleepHours' : IDL.Float64,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'interests' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'ageGroup' : IDL.Text,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHealthEntry' : IDL.Func([HealthEntry], [], []),
    'addMessage' : IDL.Func([Message], [], []),
    'addReminder' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearChatHistory' : IDL.Func([], [], []),
    'computeHealthScore' : IDL.Func([], [IDL.Nat], ['query']),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Int],
        [],
        [],
      ),
    'deleteReminder' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getHealthEntries' : IDL.Func([], [IDL.Vec(HealthEntry)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'toggleReminder' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };