/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HealthEntry {
  'bp' : string,
  'weight' : number,
  'waterIntake' : number,
  'steps' : bigint,
  'timestamp' : bigint,
  'sleepHours' : number,
}
export interface Message {
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
  'category' : string,
}
export interface Profile {
  'age' : bigint,
  'interests' : Array<string>,
  'userId' : Principal,
  'createdAt' : bigint,
  'ageGroup' : string,
}
export interface Reminder {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'createdAt' : bigint,
  'time' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHealthEntry' : ActorMethod<[HealthEntry], undefined>,
  'addMessage' : ActorMethod<[Message], undefined>,
  'addReminder' : ActorMethod<[string, string, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearChatHistory' : ActorMethod<[], undefined>,
  'computeHealthScore' : ActorMethod<[], bigint>,
  'createOrUpdateProfile' : ActorMethod<
    [bigint, string, Array<string>, bigint],
    undefined
  >,
  'deleteReminder' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<Message>>,
  'getHealthEntries' : ActorMethod<[], Array<HealthEntry>>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'toggleReminder' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];